# Generated by Django 4.2.13 on 2024-05-09 12:34

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wizardskillfarm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttimes",
            name="expiry",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="accounttimes",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounttimes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characterfarmingskill",
            name="farming_character",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farming_skills",
                to="wizardskillfarm.farmingcharacters",
            ),
        ),
        migrations.AlterField(
            model_name="farmingcharacters",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmingcharacters",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
