# Generated by Django 4.2.13 on 2024-05-23 09:09

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "wizardskillfarm",
            "0002_alter_accounttimes_expiry_alter_accounttimes_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmingskills",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmingskills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
