# Generated by Django 4.2.13 on 2024-05-23 09:19

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("wizardskillfarm", "0003_alter_farmingskills_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmingskills",
            name="skill_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmingskills",
                to="eveuniverse.evetype",
            ),
            preserve_default=False,
        ),
    ]
