# Generated by Django 4.2.13 on 2024-06-05 13:06

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("wizardskillfarm", "0007_alter_accounttimes_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DustyBotSkillQueueCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_alerted", models.DateTimeField(default=None)),
                (
                    "character",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
        ),
    ]
