# Generated by Django 4.2.18 on 2026-03-05 14:19

# Django
import django.db.models.deletion
from django.db import migrations, models


def cleanup_orphaned_skill_type_refs(apps, schema_editor):
    item_type_model = apps.get_model("eve_sde", "ItemType")
    farming_skills_model = apps.get_model("wizardskillfarm", "FarmingSkills")
    character_farming_skill_model = apps.get_model(
        "wizardskillfarm", "CharacterFarmingSkill"
    )

    db_alias = schema_editor.connection.alias

    valid_item_type_ids = item_type_model.objects.using(db_alias).values_list(
        "id", flat=True
    )

    farming_skills_model.objects.using(db_alias).exclude(
        skill_type_id__in=valid_item_type_ids
    ).delete()

    character_farming_skill_model.objects.using(db_alias).exclude(
        skill_type_id__in=valid_item_type_ids
    ).update(skill_type_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("wizardskillfarm", "0008_dustybotskillqueuecheck"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_orphaned_skill_type_refs, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="characterfarmingskill",
            name="skill_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="farmingskills",
            name="skill_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmingskills",
                to="eve_sde.itemtype",
            ),
        ),
    ]
